/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sof203.Assignment;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class QLDiemSinhVien extends javax.swing.JFrame {
    private String header[] = {"MãSV", "Họ tên", "Tiếng Anh","Tin học","GDTC","Điểm TB"};
    private DefaultTableModel tblModel = new DefaultTableModel(header, 0);
    /**
     * Creates new form QLDiemSinhVien
     */
    private ArrayList<DiemSV> list = new ArrayList<DiemSV>();
    private int currentIndex = -1;
    public QLDiemSinhVien() {
        initComponents();
        loadData();
        //SapxepDTBTang();
        loadDataToJTable();        
    }
//    private void SapxepDTBTang(){
//        DiemSV temp;
//        int min;
//        for(int i=0;i<list.size()-1;i++){
//            min=i;
//            for(int j=i+1;j<list.size();j++){
//                if(list.get(i).DiemTB < list.get(j).DiemTB)
//                    min=j;
//            }
//            //hoan vi
//            temp=list.get(i);            
//            list.set(i, list.get(min));
//            list.set(min,temp);
//        }
//    }
    public void loadDataToJTable(){
        try{
            tblModel.setRowCount(0);
            String user="sa";
            String pass="";
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            Connection con= DriverManager.getConnection(DB_URL, user, pass);
            Statement st = con.createStatement();
            String sql="select top 3 STUDENTS.MASV, Hoten, Tienganh,Tinhoc,GDTC, \n" +
                "(Tienganh + Tinhoc + GDTC)/3 as DiemTB\n" +
                "from grade, STUDENTS\n" +
                "where GRADE.MASV = STUDENTS.MASV\n" +
                "order by DiemTB desc";
            ResultSet rs= st.executeQuery(sql);
            while(rs.next()){
                Vector row = new Vector();
                row.add(rs.getString(1));
                row.add(rs.getString(2));
                row.add(rs.getString(3));
                row.add(rs.getString(4));
                row.add(rs.getString(5));
                row.add(rs.getString(6));
                tblModel.addRow(row);               
            }       
            jTable1.setModel(tblModel);
            con.close();
            
        }catch(Exception e){
            System.out.println(e);
        }
//       tblModel.setRowCount(0);
//       for(int i=0;i<3;i++){
//           DiemSV diemsv = list.get(i);
//           Vector vt = new Vector();
//           vt.add(diemsv.MASV);
//           vt.add(diemsv.Hoten);
//           vt.add(diemsv.Tienganh);
//           vt.add(diemsv.Tinhoc);
//           vt.add(diemsv.GDTC);
//           vt.add(diemsv.DiemTB);
//           tblModel.addRow(vt);
//       }
//       jTable1.setModel(tblModel);
    }
    public void UpdateDiemTB(){
        int ta = Integer.parseInt(txtDiemTA.getText());
        int th= Integer.parseInt(txtDiemTH.getText());
        int gdtc= Integer.parseInt(txtDiemGDTC.getText());
        float tb = (ta+th+gdtc)/3;
        lblDiemTB.setText(tb+"");                
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtSearchMaSV = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtDiemTA = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDiemTH = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDiemGDTC = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtMaSV = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lblDiemTB = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblTenSV = new javax.swing.JLabel();
        btnNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản Lý Điểm Snh Viên");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));

        jLabel2.setText("Mã SV:");

        btnSearch.setForeground(new java.awt.Color(51, 51, 255));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sof203/Assignment/icons/search.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearchMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearch)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btnSearch)
                .addComponent(txtSearchMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Quản Lý Điểm Sinh Viên");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Tiếng anh:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));
        jPanel2.add(txtDiemTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 110, 30));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Tin học:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));
        jPanel2.add(txtDiemTH, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 110, 30));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Giáo dục TC:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));
        jPanel2.add(txtDiemGDTC, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 110, 30));

        jLabel6.setText("Mã SV:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        txtMaSV.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtMaSV.setForeground(new java.awt.Color(0, 51, 255));
        jPanel2.add(txtMaSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 110, 30));

        jLabel7.setText("Điểm TB:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, -1, -1));

        lblDiemTB.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblDiemTB.setForeground(new java.awt.Color(51, 51, 255));
        jPanel2.add(lblDiemTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 60, 40));

        jLabel8.setText("Họ tên SV:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        lblTenSV.setBackground(new java.awt.Color(255, 51, 255));
        lblTenSV.setForeground(new java.awt.Color(0, 0, 255));
        jPanel2.add(lblTenSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 200, 30));

        btnNew.setForeground(new java.awt.Color(51, 51, 255));
        btnNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sof203/Assignment/icons/Add.png"))); // NOI18N
        btnNew.setText("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        btnSave.setForeground(new java.awt.Color(51, 51, 255));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sof203/Assignment/icons/Save.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setForeground(new java.awt.Color(51, 51, 255));
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sof203/Assignment/icons/Delete.png"))); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setForeground(new java.awt.Color(51, 51, 255));
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sof203/Assignment/icons/Edit.png"))); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnFirst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sof203/Assignment/icons/skip_backward.png"))); // NOI18N
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sof203/Assignment/icons/fast_forward.png"))); // NOI18N
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sof203/Assignment/icons/rewind.png"))); // NOI18N
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnLast.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sof203/Assignment/icons/skip_forward.png"))); // NOI18N
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel9.setForeground(new java.awt.Color(0, 51, 255));
        jLabel9.setText("3 Sinh viên có điểm cao nhất:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnFirst)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnNext)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPrevious)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLast)))
                        .addGap(42, 42, 42))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel9)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFirst, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPrevious)
                    .addComponent(btnLast)
                    .addComponent(btnNext))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String DB_URL = "jdbc:sqlserver://localhost;databaseName=SOF203;user=sa;password="; 
    public void loadData(){               
        Connection conn = null;
        Statement stmt = null;
        try {
             //Open a connection
             System.out.println("Connecting to database...");
             conn = DriverManager.getConnection(DB_URL);
             //Execute a query
             System.out.println("Creating statement...");
             stmt = conn.createStatement();
             String sql="";
             sql = "select ID, GRADE.MASV AS MASV, Hoten, Tienganh, Tinhoc, "
                     + "GDTC from GRADE, STUDENTS where GRADE.MASV = STUDENTS.MASV";
             ResultSet rs = stmt.executeQuery(sql);
             //Extract data from result set
             list.clear();
             while (rs.next()) {
               //Retrieve by column name
               int ID = rs.getInt("ID");
               String MASV = rs.getString("MASV");
               String Hoten = rs.getString("Hoten");
               int Tienganh = rs.getInt("Tienganh");
               int Tinhoc = rs.getInt("Tinhoc");
               int GDTC = rs.getInt("GDTC");
               double DiemTB = (Tienganh + Tinhoc + GDTC)/3;
               //Display values
               DiemSV diemsv = new DiemSV(ID, MASV, Hoten, Tienganh, Tinhoc, GDTC, DiemTB);
               list.add(diemsv);
             }
             // doc gia tri dau tien trong list do len form
             currentIndex = 0;
             DisplayDiemSV();  
             //Clean-up environment
             rs.close();
             stmt.close();
             conn.close();
           } catch (SQLException se) {
             //Handle errors for JDBC
             se.printStackTrace(); 
           } finally {
                 //finally block used to close resources
                 try {
                   if (stmt != null) {
                     stmt.close();
                   }
                 } catch (SQLException se2) {
                 }// nothing we can do
                 try {
                   if (conn != null) {
                     conn.close();
                   }
                 } catch (SQLException se) {
                     se.printStackTrace();
                 }//end finally try
            }//end try
        System.out.println("Done!");       
    }
    public void reset(){
        txtDiemGDTC.setText("");
        txtDiemTA.setText("");
        txtDiemTH.setText("");
        txtMaSV.setText("");
        txtMaSV.requestFocus();
    }
    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
         currentIndex = 0;
         DisplayDiemSV();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        currentIndex = list.size()-1;
        DisplayDiemSV();
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        currentIndex++;
        if(currentIndex >= list.size()){
            JOptionPane.showMessageDialog(null, "Đang ở cuối!");
            return;
        }
        DisplayDiemSV();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        currentIndex--;
        if(currentIndex < 0){
            JOptionPane.showMessageDialog(null, "Đang ở đầu!");
            return;
        }
        DisplayDiemSV();
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        int i;
        String masv;
        masv = txtSearchMaSV.getText();       
        for(i=0;i<list.size();i++){
            DiemSV diemsv = list.get(i);
            if(diemsv.MASV.equals(masv)){
                JOptionPane.showMessageDialog(this, 
                "Đã tìm thấy !", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
                currentIndex = i;
                DisplayDiemSV();
                break;
            }
        }
        if(i==list.size()){            
            JOptionPane.showMessageDialog(this, 
                "Khong tim thay !", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            txtSearchMaSV.requestFocus();
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
         String sql = "insert into GRADE (MASV,Tienganh,Tinhoc,GDTC) values(?, ?, ?, ?)";
         System.out.println(sql);
         Connection conn = null;
         PreparedStatement ps = null;
         try {
              conn = DriverManager.getConnection(DB_URL);
              ps = conn.prepareStatement(sql);
              ps.setString(1, txtMaSV.getText());
              ps.setInt(2, Integer.parseInt(txtDiemTA.getText()));
              ps.setInt(3, Integer.parseInt(txtDiemTH.getText()));
              ps.setInt(4, Integer.parseInt(txtDiemGDTC.getText()));
              // Thực thi câu lệnh insert
              ps.execute();              
              JOptionPane.showMessageDialog(this, "Insert thành công!"); 
              loadData();
              //SapxepDTBTang();
              loadDataToJTable();
         } catch (Exception e) {
              e.printStackTrace();
              JOptionPane.showMessageDialog(this, "Insert Fail ...");
         } finally {
               try {
                    if (conn != null) {
                     conn.close();
                    }
                    if (ps != null) {
                     ps.close();
                    }
               } catch (Exception ex2) {
                ex2.printStackTrace();
               }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
         String sql = "delete from GRADE where MASV=?";
         System.out.println(sql);
         Connection conn = null;
         PreparedStatement ps = null;
         try {
              conn = DriverManager.getConnection(DB_URL);
              ps = conn.prepareStatement(sql);
              ps.setString(1, txtMaSV.getText());              
              ps.execute();              
              JOptionPane.showMessageDialog(this, "Delete thành công!");
              loadData();
              //SapxepDTBTang();
              loadDataToJTable();
         } catch (Exception e) {
              e.printStackTrace();
              JOptionPane.showMessageDialog(this, "Fail ...");
         } finally {
               try {
                    if (conn != null) {
                     conn.close();
                    }
                    if (ps != null) {
                     ps.close();
                    }
               } catch (Exception ex2) {
                ex2.printStackTrace();
               }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
         String sql = "update GRADE set Tienganh = ?, Tinhoc = ?, GDTC = ? where MASV=?";
         System.out.println(sql);
         Connection conn = null;
         PreparedStatement ps = null;
         try {
              conn = DriverManager.getConnection(DB_URL);
              ps = conn.prepareStatement(sql);
              ps.setInt(1,Integer.parseInt(txtDiemTA.getText()));
              ps.setInt(2,Integer.parseInt(txtDiemTH.getText()));
              ps.setInt(3,Integer.parseInt(txtDiemGDTC.getText()));
              ps.setString(4, txtMaSV.getText());              
              ps.execute();              
              JOptionPane.showMessageDialog(this, "Update thành công!");  
              loadData();
              //SapxepDTBTang();
              loadDataToJTable();
         } catch (Exception e) {
              e.printStackTrace();
              JOptionPane.showMessageDialog(this, "Fail ...");
         } finally {
               try {
                    if (conn != null) {
                     conn.close();
                    }
                    if (ps != null) {
                     ps.close();
                    }
               } catch (Exception ex2) {
                ex2.printStackTrace();
               }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLDiemSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLDiemSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLDiemSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLDiemSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QLDiemSinhVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblDiemTB;
    private javax.swing.JLabel lblTenSV;
    private javax.swing.JTextField txtDiemGDTC;
    private javax.swing.JTextField txtDiemTA;
    private javax.swing.JTextField txtDiemTH;
    private javax.swing.JTextField txtMaSV;
    private javax.swing.JTextField txtSearchMaSV;
    // End of variables declaration//GEN-END:variables

    private void DisplayDiemSV() {
        DiemSV diemsv =   list.get(currentIndex);
        txtMaSV.setText(diemsv.MASV+"");
        lblTenSV.setText(diemsv.Hoten+"");
        txtDiemTA.setText(diemsv.Tienganh+"");
        txtDiemTH.setText(diemsv.Tinhoc+"");
        txtDiemGDTC.setText(diemsv.GDTC+"");
        
        UpdateDiemTB();
    }

    
}
